### ISSUE TITLE
Remote control not working

### ISSUE THREAD

**Issue by Julmath** [Koenvh1/ets2-local-radio#103]
Hi there, thanks for you wonderful work as always.
I tried today for the first time to access remote control on my iPhone, but it didn't work even after following your indications. "Safari can't open the webpage because the server has stopped answering" or something like that.
Any idea on what could cause it?

**Comment by Koenvh1** [comment]
Are your phone and computer connected to the same network? Also make sure to enter http://localradio.koenvh.nl/?api=... as your URL (not sure whether I updated that properly in the readme)

**Comment by Julmath** [comment]
Yup, everything is connected on the same network. I’ve tried both methods (with localradio.koenvh.nl and with 192.168.etc directly), with 192 directly nothing loads (I suppose that’s expected now haha, but yeah your readme isn’t up to date). With localradio etc, the interface loads correctly but I can’t establish a connection with the one on my PC as entering the PeerID doesn’t do anything...

________________________________
Da: Koen <notifications@github.com>
Inviato: Sunday, June 7, 2020 11:48:07 PM
A: Koenvh1/ets2-local-radio <ets2-local-radio@noreply.github.com>
Cc: Julien Mathias <julien.mathias@outlook.com>; Author <author@noreply.github.com>
Oggetto: Re: [Koenvh1/ets2-local-radio] Remote control not working (#103)


Are your phone and computer connected to the same network? Also make sure to enter http://localradio.koenvh.nl/?api=... as your URL (not sure whether I updated that properly in the readme)

**Comment by Koenvh1** [comment]
I have updated the library used for the remote control, so hopefully it works now. If it doesn't, please make sure that it is not caused by your browser or plugins. E.g. that you have an addon that disables WebRTC or something (some privacy addons do that).

**Comment by Julmath** [comment]
That was it, it's fixed, though it disconnects quite quickly. Thank you very much!
