### ISSUE TITLE
A part of Promods 2.51 Maps missing

### ISSUE THREAD

**Issue by VoXaN24** [Koenvh1/ets2-local-radio#129]
![image](https://user-images.githubusercontent.com/30030208/107125205-c131e880-68a8-11eb-839b-446a594b571d.png)
All syria and a little part of Turkey is missing (Idk how take the coordonate of the city for added the support)

**Comment by Koenvh1** [comment]
Could very well be that I forgot a part of the cities from ProMods ME 2.51.
I will add them, or if you are interested in doing it yourself, this is the tool I use to generate those city coordinates: 
https://github.com/Koenvh1/ETS2-City-Coordinate-Retriever

**Comment by VoXaN24** [comment]
Oh, I doing that when i can
