### ISSUE TITLE
Overlay crashes both games.

### ISSUE THREAD

**Issue by hadeseol** [Koenvh1/ets2-local-radio#136]
In the latest update for both games I'm having an issue in where when the overlay is supposed to show on screen. Eg. when the program recognizes the truck location and the station starts playing. If I leave the program open and restart the game, the game won't crash but won't show the overlay either, the rest works normally with stations changing depending on the area.

**Comment by Koenvh1** [comment]
Restarting the game will break the overlay. Whenever it loads the overlay, it checks whether it knows the ETS2/ATS process. If not, it will try to find it. If you restart the game, it will still remember the old process, thus it will try to overlay it there (which you cannot see, obviously).

I have created a possible fix here:
[Release.zip](https://github.com/Koenvh1/ets2-local-radio/files/6232017/Release.zip)

Fully untested however, so I have no idea whether it actually works.

**Comment by Koenvh1** [comment]
I was already wondering what the crash meant in the title. Anyhow, I'm not sure what is happening. Have you tried uninstalling it, removing the folder itself (sometimes it doesn't remove everything), and installing it again?

**Comment by hadeseol** [comment]
After trying some options, I seem to have found the culprit. I tried rolling back the Nvidia drivers since that was the only thing that changed as they were updated yesterday. After rolling back the drivers the issue seems to be solved. So it seems at least in my case that the new Nvidia drivers have compatibility issues with the overlay function of the program.

**Comment by hadeseol** [comment]
Well I finally found the real culprit in my case after much testing. For me it started to conflict with RivaTuner Statistics Server. It works fine as long as I launch RivaTuner after loading the truck. I would guess it would also cause issues for anyone using MSI Afterburner as both use similar code.
