### ISSUE TITLE
SlimDX.dll error on start

### ISSUE THREAD

**Issue by kowal-dev** [Koenvh1/ets2-local-radio#144]
Installed from installer and started software. It showed up that error
![Annotation 2021-06-30 120521](https://user-images.githubusercontent.com/73757184/123943013-fcd66780-d99b-11eb-8f22-f514ade88f57.png)
Dll is in folder and replacing it is not helping. Please help!

**Comment by Koenvh1** [comment]
https://github.com/Koenvh1/ets2-local-radio#the-server-wont-start-due-to-some-slimdxdll-problem
