### ISSUE TITLE
Game freezes after playing radio

### ISSUE THREAD

**Issue by roughnecks** [Koenvh1/ets2-local-radio#147]
Hi,

I don't know if I'm doing it wrong but I don't see a "play" shortcut, so I'm running the radio, open it on my browser and then I fire up ETS2. When I'm in-game I switch to my browser where the stations are populated now and start playing one.. When I alt-tab back to game, it's often frozen with no means of controlling it (mouse/KB/pad), so I have to stop it with the button on Steam and start it up again; at this point everything works.

**Comment by Koenvh1** [comment]
Does this also happen when the overlay is disabled in the settings?

**Comment by roughnecks** [comment]
> Does this also happen when the overlay is disabled in the settings?

where is this setting?

**Comment by Koenvh1** [comment]
`settings.json` file in your installation folder. You might need to open your text editor with administrator rights depending on where you installed it.

**Comment by roughnecks** [comment]
Just changed it to false and fired up the game.. This time it worked as expected.
Will let you know if it happens again.

Thanks

**Comment by Koenvh1** [comment]
The overlay seems to work for most people (including me), but for some it seems to cause crashes. I have no idea why.
