### ISSUE TITLE
Google Chrome 93 - Radio or website not working, error in console

### ISSUE THREAD

**Issue by JaffaKetchup** [Koenvh1/ets2-local-radio#149]
This is the error:
> Access to XMLHttpRequest at 'http://192.168.56.1:8330/commands/' from origin 'http://localradio.koenvh.nl' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.

That same error is also replicated for '/api'.

Going to [192.168.56.1:8330/commands]() or [192.168.56.1:8330/api]() works fine, but this parent site can't access it.

However, using Edge seems to work fine.

**Comment by Koenvh1** [comment]
Related: https://developer.chrome.com/blog/private-network-access-update/

**Comment by JaffaKetchup** [comment]
That explains it, because I use Chrome Dev, so it's a version ahead of stable.

Thanks,

Luka S


________________________________

**Comment by Koenvh1** [comment]
I am not surprised, but I will have to look into fixing this. I do have plans for a long-term solution, but it seems like a short-time fix is needed as well.
