### ISSUE TITLE
Overlay in OBS

### ISSUE THREAD

**Issue by roughnecks** [Koenvh1/ets2-local-radio#158]
Hello,
is there a way to add Local Radio's overlay to OBS?

Thanks

**Comment by Koenvh1** [comment]
Do you mean temporarily (when changing) or permanently? Both are probably possible, although the latter is much easier than the former.

Just as a word of warning: if you are streaming with Local Radio, then you can be guaranteed that your account will get a copyright strike if you do not have the appropriate licences, which might be difficult to determine for live radio.

**Comment by roughnecks** [comment]
Well, when changing would be better; can you explain how to do that?
And, don't worry, I have the VOD Track on OBS, set to exclude my music :-)

Now that I think about it, tho, viewers will see the station changing but no music! Not sure that's what I want.. hmm

**Comment by Koenvh1** [comment]
Just to check, you did turn on "Capture third-party overlays", right?
![afbeelding](https://user-images.githubusercontent.com/5168825/131919648-4c8eacd6-276a-4522-a7c1-9e5e4a01ba26.png)

**Comment by roughnecks** [comment]
> Just to check, you did turn on "Capture third-party overlays", right?

No, I haven't because I wouldn't like to show Steam's overlay?
Do I just have to turn that on?

**Comment by Koenvh1** [comment]
OBS can't see a difference between Steam and Local Radio, so it disables both. You _could_ work around that by adding a browser control, adding a call to the place where the overlay is [normally](https://github.com/Koenvh1/ets2-local-radio/blob/master/web/lib/js/main.js#L396) called from, and then using that browser control to display whatever you want. Sounds more complex than it is, but not a walk in the park either.

**Comment by roughnecks** [comment]
I don't think I can do this by myself, but thanks anyway 👍
