### ISSUE TITLE
There is a station that I can no longer listen to

### ISSUE THREAD

**Issue by kaz-ets2** [Koenvh1/ets2-local-radio#170]
I can't hear Romanian "itsybitsy" anymore. I was able to hear it a while ago. Thank you.

**Comment by Koenvh1** [comment]
Yup. Their certificate expired six days ago. It'll resolve itself once Itsy Bitsy FM fixes their stream. I also sent them an email to speed things up a bit.

**Comment by kaz-ets2** [comment]
Thank you very much. Thanks to this application, I was able to know many radio stations. Thank you for your future support.
