### ISSUE TITLE
Opening ETS2 Local Radio Web Pages causes ETS to crash

### ISSUE THREAD

**Issue by daveo132** [Koenvh1/ets2-local-radio#173]
Hi,
New to ETS and to this app.
I have it installed as per the instructions and the app successfully shows me in the game etc.
However, the moment I click on _"Open ETS2 Local Radio"_ the game crashes to desktop.

I do have a modded install however all of the mods are for Traffic etc except for Promods maps which appears to be supported.

For some reason my URL has 2 address?

![image](https://user-images.githubusercontent.com/96916642/147828228-850b5692-2b95-48b1-9ebb-e79bc92ef472.png)

Please let me know if I can supply any more info to help with this (or fix my own issue).
Thanks.

**Comment by Koenvh1** [comment]
Have you tried turning the overlay off (in the settings file)?

Once the page loads, the overlay will be shown for the current station. The overlay crashes for some, so I expect that is the cause.

**Comment by daveo132** [comment]
I have not, i will give it a try and report back.  Thanks and happy new year.

**Comment by daveo132** [comment]
that fixed it thanks!
