### ISSUE TITLE
Game Crash with error message

### ISSUE THREAD

**Issue by djangoscroll** [Koenvh1/ets2-local-radio#177]
Hi
Bonjour,
J'ai ce message d'erreur lorsque je veux allumer la radio.
![image](https://user-images.githubusercontent.com/93676627/152797320-1e45081c-7b01-4565-a7a3-d7f3068dd61d.png)
![image](https://user-images.githubusercontent.com/93676627/152798342-e1af117f-2187-4325-8624-31990bfea37c.png)

[Error log.txt](https://github.com/Koenvh1/ets2-local-radio/files/8015614/Error.log.txt)

Merci

**Comment by Koenvh1** [comment]
Bonjour,

I don't speak French, but I am not sure whether that error is caused by Local Radio. The overlay may cause crashes, but generally without error message. Still worth a try: https://github.com/Koenvh1/ets2-local-radio/issues/176 https://github.com/Koenvh1/ets2-local-radio/issues/173

**Comment by djangoscroll** [comment]
Hi
Thanks it works ! Don't know for this error message, even on french it means nothing 🤣
Awesome for immersive game, hope you can fix this.
