### ISSUE TITLE
Missing error message when setting the same key for an action.

### ISSUE THREAD

**Issue by Ticreut29** [Koenvh1/ets2-local-radio#179]
For some reason, If you set the same key for an action exemple: next station key is page up and previous station key is page up nothing happen, not even an error is appearing in that case telling it's not possible to have the same key
[https://imgur.com/B73ljdi](url)

**Comment by Koenvh1** [comment]
In principle it is possible to bind the same key to two actions, however, the web interface will most likely not react quickly enough to process it. I do not directly see a use case for binding one key to two actions, but I also have no reason to bar you from doing silly things.
