### ISSUE TITLE
Radio play not automaticly

### ISSUE THREAD

**Issue by errorflash** [Koenvh1/ets2-local-radio#181]
I have install since a year ago after systemupgrade ats and local radio.

I use for open a Batch file.

1. start from local Radio
2. wait 1 second
3. open Microsoft edge and open Radio website
4. wait 2 seconds
5. open ATS

at the last time when i use the batch the radio plays automaticly the first station when the website get a GPS Signal from ATS.
Now is the situation i must make a interaction with the website then play the music.
I use Windows 11 with the newest updates. I have try opera and have the same issue.

**Comment by Koenvh1** [comment]
At least for Edge, you should be able to add an exception for Local Radio here: [edge://settings/content/mediaAutoplay](edge://settings/content/mediaAutoplay). Opera likely has something similar.

**Comment by errorflash** [comment]
Ah OK!

Thats clear my issue! Thanks!
