### ISSUE TITLE
ETS2 Local Radio isn't detecting ETS2 

### ISSUE THREAD

**Issue by HaeckelL06** [Koenvh1/ets2-local-radio#184]
As mentioned in the title, Local Radio does not find ETS2 even though it is running.

Suggested solutions from this area: https://github.com/Koenvh1/ets2-local-radio/issues/157
and from: https://github.com/Koenvh1/ets2-local-radio#it-says-the-simulator-is-not-running-even-though-it-is
have not helped. 

Error is the following:
00:00:18.261 : loading 'ets2-telemetry' '/Euro Truck Simulator 2/bin/win_x86/plugins/ets2-telemetry.dll'
00:00:18.262 : unable to load: 0000007E
And installing "Visual C++ Redistributable for Visual Studio 2015" doesn't work because I've already installed a newer version.

Installed Version of ETS2: 1.45.x
Installed Version of Local Radio: v3.3.1
Used Language: de-DE

[game.log.txt](https://github.com/Koenvh1/ets2-local-radio/files/9363765/game.log.txt) can be found here 

Would be great if someone could help me

**Comment by Koenvh1** [comment]
>  And installing "Visual C++ Redistributable for Visual Studio 2015" doesn't work because I've already installed a newer version.
Microsoft is not really clear regarding this, but these run alongside each other (i.e. Visual C++ Redistributable for Visual Studio 2022 does not replace all the ones that came before it). Also make sure it's the x86 (32-bit) version.

**Comment by HaeckelL06** [comment]
When I try to install Visual C++ Redistributable for Visual Studio 2015 (regardless of whether it is x64 or x86) I always get the error 0x80070666 and I have to cancel the setup. What should i do now?

**Comment by NigeUK** [comment]
Try the steps here:

https://appuals.com/fix-0x80070666-when-installing-microsoft-visual-c/

Apologies for butting in!

**Comment by Koenvh1** [comment]
Ah great, it seems they finally started to bundle 2015-2022 as one installation. Did you try the alternative one? https://github.com/Koenvh1/ets2-local-radio/tree/master/plugins/alternative_ets2-telemetry.dll
It's the same as the standard one, except compiled with another version of MSVC.

**Comment by HaeckelL06** [comment]
> https://appuals.com/fix-0x80070666-when-installing-microsoft-visual-c/

Now I can install it but change still nothing

> Did you try the alternative plugin dll? 

That was probably the mistake. Now it runs without problems

Thanks to both of you for helping
