### ISSUE TITLE
[bug] custom radio logo not working with default settings\server

### ISSUE THREAD

**Issue by Radiquum** [Koenvh1/ets2-local-radio#188]
**description:**

when adding your own radio station with a standard server (url-prefix) `http://localradio.koenvh.nl/`, its logo is not shown, because the link takes the form like `http://localradio.koenvh.nl/file_path/logo.png` or `http://localradio.koenvh.nl/http://url/logo.png`

also because of this, station is not showing at all in in-game overlay (related: issue #131)

examples on the web ui:

![image](https://user-images.githubusercontent.com/68120017/186306726-23455a06-9b98-4716-ba77-3a823d2b85d3.png)

![image](https://user-images.githubusercontent.com/68120017/186307057-9800ac27-7f0b-4be5-9a04-db6146798123.png)

if the url-prefix is empty, then all other radio stations logos are not found

**solutions:**

1. (user) empty the `url-prefix` in config.js, then download 'web/stations' folder from github, and place it into the `local radio/web' manually, but then stations logos will be needed to be updated every time with the new stations updates\additions from developer
2. (developer) remove adding `url-prefix` to logo url for custom stations

p.s. anyway it's a great application, keep up the good work <3

**Comment by Koenvh1** [comment]
First of all: thank you for the extensive report. I wish all of them were like this :-)

It seems I have been a bit overzealous with the `url-prefix` without taking non-local stations into account. Should be relatively simple to fix.

**Comment by Koenvh1** [comment]
I did not test it extensively yet, but https://github.com/Koenvh1/ets2-local-radio/commit/c7decaef48a62c6eed4432ae9ccdb14d48672a12 should fix the issue. You should be able to replace the `web/lib/main.js` file with this version if you want to test it yourself.

**Comment by Radiquum** [comment]
yep, it's fixed now, thank you :3
