### ISSUE TITLE
Language status

### ISSUE THREAD

**Issue by Koenvh1** [Koenvh1/ets2-local-radio#19]
Languages fully up-to-date (v1.18):
- [x] be-BY
- [ ] cs-CZ
- [x] da-DK
- [x] de-DE
- [x] en-GB
- [x] en-US
- [ ] es-ES
- [ ] et-EE
- [x] fi-FI
- [x] fr-FR
- [ ] fun-NG
- [x] gr-GR
- [x] it-IT
- [x] ja-JP
- [ ] lt-LT
- [x] lv-LV
- [x] nl-NL
- [x] pl-PL
- [ ] pt-BR
- [x] ru-RU
- [x] sk-SK
- [x] sv-SE
- [ ] tr-TR

Could you also look at it @dobasy and @tohaklim ?

**Comment by DarkArtek** [comment]
Updated the italian Language

**Comment by Koenvh1** [comment]
I added a new string:
```
"broken-station": "Report a broken station"
```
(line 16)

Languages fully up-to-date (v1.19):
- [ ] be-BY
- [ ] cs-CZ
- [ ] da-DK
- [ ] de-DE
- [x] en-GB
- [x] en-US
- [ ] es-ES
- [ ] et-EE
- [ ] fi-FI
- [ ] fr-FR
- [ ] fun-NG
- [ ] gr-GR
- [ ] it-IT
- [ ] ja-JP
- [ ] lt-LT
- [ ] lv-LV
- [x] nl-NL
- [ ] pl-PL
- [ ] pt-BR
- [ ] ru-RU
- [ ] sk-SK
- [ ] sv-SE
- [ ] tr-TR

Could you have a look at it @dobasy @DarkArtek @tohaklim @Tim3game @Julmath @UnexcitingDean ?

**Comment by DarkArtek** [comment]
Ok, adding the translation
