### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by Ftamino** [Koenvh1/ets2-local-radio#190]
Please make a version for linux

**Comment by Koenvh1** [comment]
There is an older version for Linux - not sure if it still works: https://github.com/Koenvh1/ets2-local-radio/pull/135. I'm more than happy to add support if someone else creates a stable Linux version, but I do not have a machine to test it on currently.

**Comment by Ftamino** [comment]
Ok ill try to get that older version working or **try** making a stabel ine

**Comment by jh-devv** [comment]
I think a Proton supported/guide for Proton would be better, ETS2 performs at least for me, *far* better on Proton!
