### ISSUE TITLE
Virgin radio name has changed in France

### ISSUE THREAD

**Issue by Jet64100** [Koenvh1/ets2-local-radio#197]
Hello, Virgin radio doesn't exist any more in France.
It has been replaced by Europe 2.

Could you change the radio icon and name ?

Thanks !

**Comment by Koenvh1** [comment]
@04Marcus Could you test whether the following stream URL still works? (It currently works for me, but I am not sure if the session expires at some point)
https://europe2.lmn.fm/europe2-live/playlist.m3u8?aw_0_1st.playerid=lagardereappEurope2&aw_0_req.userConsentV2=CPlREsAPlREsAAHABBENCxCgAP_AAAAAAAAAHqtf_T__b39h8359_-t0eYlf5-7_uu0zhhfdBy4Nyc_XuL0X_2MruF34hqYKoR4ks3LBIQdlFOHcDUGwyoAVrTPsbkyMh7JKJ7OEmnMQewdYGFt3nx3TyZKYi7_bf_Zru3a_1-7-5-_5vuvf_vt5_7_3-bf_V_l96dn9f-AAAAkNABgACCTIqADAAEEmQkAGAAIJMiIAMAAQSZGQAYAAgkyOgAwABBJkhABgACCTJKADAAEEmSkAGAAIJMgA.f_gAAAAAAAAA

The logo can be found here by the way:
https://upload.wikimedia.org/wikipedia/commons/c/c4/E2-LOGO-FOND-NOIR.svg?uselang=fr
