### ISSUE TITLE
Software only supports one controller

### ISSUE THREAD

**Issue by MathijsG** [Koenvh1/ets2-local-radio#2]
I always have my joystick plugged in, and when I'm driving I plug in the G27 as an extra controller. This software however only recognizes the joystick, but doesn't respond to the G27 controller.

**Comment by Koenvh1** [comment]
I added support for a different controller than the first, will look to support multiple controllers as well, but I can't tell you when that will be available.

**Comment by MathijsG** [comment]
I think choosing the preffered controller is already good enough for me! :)

**Comment by Koenvh1** [comment]
Should now - finally - work properly 😄
