### ISSUE TITLE
Local Radio doesn't work

### ISSUE THREAD

**Issue by Marsoff9898** [Koenvh1/ets2-local-radio#220]
I get timed out connection issues when I open the Local Radio browser overlay so I can't play any stations or something.

**Comment by Koenvh1** [comment]
My guess is that you have a firewall that blocks connections to yourself, or have a different application that uses port 8330. You can always try opening [http://localhost:8330](http://localhost:8330) or change the port number in the `settings.json` file.

**Comment by Marsoff9898** [comment]
Sorry. It was my antivirus firewall.
-------- Mensaje original --------De: Koen van Hove ***@***.***> Fecha: 15/1/24  17:47  (GMT-03:00) A: Koenvh1/ets2-local-radio ***@***.***> CC: Marsoff9898 ***@***.***>, Author ***@***.***> Asunto: Re: [Koenvh1/ets2-local-radio] Local Radio doesn't work (Issue #220) 
My guess is that you have a firewall that blocks connections to yourself, or have a different application that uses port 8330. You can always try opening http://localhost:8330 or change the port number in the settings.json file.
