### ISSUE TITLE
Keep getting SlimDX error, even though 2010 service package is installed

### ISSUE THREAD

**Issue by Markosha2004** [Koenvh1/ets2-local-radio#230]

**Comment by J-e-g-g-e** [comment]
Just had the same problem, solved it by downloading and installing vcredist_x86.exe.

you can get it here: https://www.microsoft.com/en-us/download/details.aspx?id=26999

**Comment by Markosha2004** [comment]
> Just had the same problem, solved it by downloading and installing vcredist_x86.exe.
> 
> you can get it here: https://www.microsoft.com/en-us/download/details.aspx?id=26999

I'll try it tomorrow, thanks

**Comment by Markosha2004** [comment]
yup, 32 bit solved it
