### ISSUE TITLE
(Android 14) NET::ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by Markosha2004** [Koenvh1/ets2-local-radio#231]
As tittle implies, I can't use mobile app because of that error. Any workarounds?

**Comment by Koenvh1** [comment]
Something probably broke when I released an update to target the latest Android SDK (if I don't it gets removed from Google Play). Can probably fix, in the meantime just use a browser or something like https://play.google.com/store/apps/details?id=de.ozerov.fully

**Comment by Markosha2004** [comment]
Hi, can't resolve it with Fully Kiosk, getting net::ERR_CONNECTION_REFUSED

**Comment by Koenvh1** [comment]
The app should now be fixed
