### ISSUE TITLE
When will it support https?

### ISSUE THREAD

**Issue by Wogahn** [Koenvh1/ets2-local-radio#239]
This is the best plugin for ets and ats i really like it. Makes the game experience much richer.
But unfortunately it is http which isn't safe at all.
Do you all have any plan about changing this?
![Capture](https://github.com/user-attachments/assets/cc3a8780-fd03-4279-8870-895da0a40492)

**Comment by Koenvh1** [comment]
Pages loaded over HTTPS are not allowed to load in sources loaded over HTTP. I could make the webserver HTTPS (although you'd have to accept the self-signed certificate), but I can't make every radio station in Local Radio support HTTPS. So all of them that are not HTTPS would stop working.

**Comment by Wogahn** [comment]
Perhaps you could create a https version that only loads https radios. While still maintain the currently http version that loads both.
Sorry if this not a possible suggestion, i dont understand anything about programming^^

**Comment by Koenvh1** [comment]
It would still leave this message when you first load the page:
![Jm7sF](https://github.com/user-attachments/assets/3a8190cd-bc10-4ce7-b5e0-4982b0bdc819)

To give you some statistics: 
- For ETS2, there are 370 HTTP stations and 1095 HTTPS stations. 
- For ATS, there are 3743 HTTP stations and 9388 HTTPS stations. 

So you would be missing out on roughly ¼ of all stations.

**Comment by Wogahn** [comment]
It's fine to a have message like.. Informing that not all radios will work on https version of the page.
And therefore the page load all these https stations.
Even though local radio might be trusty. When in a http website the traffic can be easily intercepted by something malicious.
Also happend once to me when i switched to a different radio and the antivirus showed an alert...

But anyways, sorry for anything and thanks a lot for the informations and reply. Take care Koenvh ;)
