### ISSUE TITLE
Cities from ItalyMap?

### ISSUE THREAD

**Issue by Julmath** [Koenvh1/ets2-local-radio#28]
I was wondering if it would be possible for you to add support for the cities from ItalyMap?
Someone released a fix in order to make it compatible with Promods, so it would be great to add its cities here.

You have the list of the new cities [here](https://www.promods.net/viewtopic.php?f=42&t=16573).

**Comment by Koenvh1** [comment]
Done, will be there in the next version 😃 
https://github.com/Koenvh1/ets2-local-radio/commit/01c56498e46177fcdc5e0dad020ed0851958ae3d
