### ISSUE TITLE
Newest version doesn't work with G27 steering wheel

### ISSUE THREAD

**Issue by MathijsG** [Koenvh1/ets2-local-radio#3]
The software doesn't work anymore with my G27 wheel somehow. It just doesn't do anything when I'm pressing the buttons to map them.

How can I debug something for you?

**Comment by skipper00123** [comment]
HI, if you still have that problem , i think there's a way around it ,, map the controls on the keyboard ,, and use Xpadder software to assign joystick buttons to works as keyboard buttons,  e.i,  Num0, is pause ,, in xPadder assign Button 1  as Num0,, voila, you can control it with the controller now !

**Comment by MathijsG** [comment]
Maybe it was some weird one-time issue, because now the pressess do get registered. However I found out my media keys on my keyboard were more convenient for use.
