### ISSUE TITLE
Iron already started

### ISSUE THREAD

**Issue by MathijsG** [Koenvh1/ets2-local-radio#4]
I downloaded the new version and I can't start it, it says it's already started, while having no such process. When I manually want to start the executable I get the same problem.

![image](https://cloud.githubusercontent.com/assets/529552/21955632/762334fa-da6f-11e6-806c-fcd118afc979.png)

**Comment by Koenvh1** [comment]
Not sure why this happens... I will try to find a solution, but as it is a temporary fix, I may just leave it be. Don't want to spend too much time on it. What I did do is make version 1.5.1 the latest version again, and added 1.5.2 as an optional fix.

**Comment by Koenvh1** [comment]
Removed Iron from the project.
