### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by CookiePLMonster** [Koenvh1/ets2-local-radio#48]
Where does this d3d9.dll come from? Is it a proprietary overlay plugin or is it available anywhere? I'm beyond curious on what causes this nasty exit crash and what the "alternative" DLL changes so it works fine..

**Comment by Koenvh1** [comment]
It is available here: http://www.mikoweb.eu/?page_id=54
The original one is open source; I'm not sure about the alternative one. You're better off asking him, but I believe it had something to do with the way ETS2 unloads frames.
