### ISSUE TITLE
Error reading JObject from JsonReader. Path ", line 1, position 727.?

### ISSUE THREAD

**Issue by radek167** [Koenvh1/ets2-local-radio#52]
Hello! I have a problem. Today I wanted to launch this program (ETS 2 Local Radio), but when it boots, it shows a problem (it's in polish language)

"Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just in time)
zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

************** Tekst wyjątku **************
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 727.
   w Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   w Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   w Newtonsoft.Json.Linq.JObject.Parse(String json)
   w ETS2_Local_Radio_server.Settings.Load()
   w ETS2_Local_Radio_server.Main.Main_Load(Object sender, EventArgs e)
   w System.Windows.Forms.Form.OnLoad(EventArgs e)
   w System.Windows.Forms.Form.OnCreateControl()
   w System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   w System.Windows.Forms.Control.CreateControl()
   w System.Windows.Forms.Control.WmShowWindow(Message& m)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   w System.Windows.Forms.Form.WmShowWindow(Message& m)
   w System.Windows.Forms.Form.WndProc(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Zestawy załadowane **************
mscorlib
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2115.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ETS2 Local Radio server
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/ETS2%20Local%20Radio%20server.exe
----------------------------------------
System.Windows.Forms
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SlimDX
    Wersja zestawu: 4.0.13.43
    Wersja Win32: 
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/SlimDX.DLL
----------------------------------------
Ets2SdkClient
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/Ets2SdkClient.DLL
----------------------------------------
Newtonsoft.Json
    Wersja zestawu: 9.0.0.0
    Wersja Win32: 9.0.1.19813
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.CSharp
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Windows.Forms.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Debugowanie w trybie JIT **************
Aby włączyć debugowanie w trybie just in time (JIT), plik .config tej
aplikacji lub komputera (machine.config) musi mieć
wartość jitDebugging ustawioną w sekcji system.windows.forms.
Aplikacja musi być również skompilowana z włączonym
debugowaniem.

Na przykład:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Gdy debugowanie JIT jest włączone, wszystkie nieobsługiwane wyjątki
są wysyłane do debugera JIT zarejestrowanego na komputerze
i nie są obsługiwane w tym oknie dialogowym."

What's went wrong? Can anyone help me?

Best regards, 
Radek.

**Comment by Koenvh1** [comment]
Could you go into the ETS2 Local Radio installation folder, remove the settings.json file, and start it again?

**Comment by radek167** [comment]
It works! Thanks so much!

**Comment by Rayzer78** [comment]
I recently re-installed my  OS and was using this mod (along with dashboard telementary plugin) on the previous build without any real issues. However, even  after reading troubleshooting guide I have been banging my head against a brick-wall in trying to get the ETS 2 local radio  to work on the current system. I have reinstalled all the redistributables with out any success.

**Comment by Koenvh1** [comment]
Does this relate to this issue? If not, then please create a new issue
instead with details what goes wrong and what you tried - it helps to keep
the overview

Op ma 12 aug. 2019 om 22:27 schreef Rayzer78 <notifications@github.com>:

**Comment by Rayzer78** [comment]
Apologies I will create a new issue with the  game log.
