### ISSUE TITLE
Bandit Rock/Lugna Favoriter (stations in Sweden) asking for login

### ISSUE THREAD

**Issue by Qrusher14242** [Koenvh1/ets2-local-radio#66]
they ask me for a login when i try to play it. It says:

http://fm02-icecast.mtg-r.net is requesting your username and password

then wont play.

**Comment by Koenvh1** [comment]
What country are you currently residing in (/is your internet connection using)? It might be that specific countries are geoblocked.

**Comment by Qrusher14242** [comment]
im in USA and using Charter/Spectrum cable. Yeah it could be blocking me, didnt think of that. I havent seen that before, so wasnt sure.

**Comment by Koenvh1** [comment]
I tested it, and here are my results:

| Country | Blocked? |
|-------------|----------|
| US East | Yes |
| Canada East | No |
| France | No |
| Netherlands | No |
| Hong Kong   | No |

So not sure why they decided to just block USA.
