### ISSUE TITLE
non-local ads breaks immersion

### ISSUE THREAD

**Issue by superfreeman1989** [Koenvh1/ets2-local-radio#68]
I've noticed after a while when you switch station, it plays a 30s ads before stream starts playing. The ads is based on your ip address so it's not local ads where the station is broadcast. This 30s ads plays EVERY TIME you switch station and is really annoying and breaks immersion. Is there anyway to remove or block it?

**Comment by Koenvh1** [comment]
This is part of the station's radio stream in a few cases, so unfortunately there is no way to get around this.
