### ISSUE TITLE
Add support for Linux

### ISSUE THREAD

**Issue by Koenvh1** [Koenvh1/ets2-local-radio#75]
Since the Linux version of ETS2 and ATS now support Linux, it might make sense to also create a (simpler) Linux version.

Things that need to be done:
- [ ] Extract the telemetry from the [example](https://modding.scssoft.com/wiki/Documentation/Engine/SDK/Telemetry) using a memory mapped file.
- [ ] Read the mmap file with Python/Java (or something else), and serve it on an HTTP server
- [ ] Serve the rest of the web front-end on the server as well

Keyboard/controller controls, GUI, overlay etc. can be added in a later stage.

**Comment by Kaperios** [comment]
No Linux build for 1.41.0 build?

**Comment by Koenvh1** [comment]
There is now

**Comment by Kaperios** [comment]
1.42 - No Linux build

**Comment by Koenvh1** [comment]
The release was rushed because of other obligations, so hence I released
what I had (as a beta).
Consequently, there was no Linux version, though you can create it yourself
by replacing the `web` folder from the Linux version by the new version.
I do intend to create a proper Linux version (maybe one that can update
itself), but I'm not there yet unfortunately.

Op za 18 mei 2019 om 10:26 schreef Kaperios <notifications@github.com>:

**Comment by Kaperios** [comment]
Was there any progress on Linux build recently? Also, 2.0.0 is a major release version so imo it should have a Linux build.

**Comment by Koenvh1** [comment]
No, though feel free to make a pull request.
