### ISSUE TITLE
Coverage in Vilnius

### ISSUE THREAD

**Issue by Airavaandrel** [Koenvh1/ets2-local-radio#76]
Vilnius has very poor coverage. Is it possible to adjust that?

**Comment by Koenvh1** [comment]
Will be solved by https://github.com/Koenvh1/ets2-local-radio/commit/45cee8e533798c3426714b68f5413a7a7bb99b9c which will be included in the next version.
If you want to fix it before that, you can replace your /web/cities/cities-ets2.js file with this version: https://github.com/Koenvh1/ets2-local-radio/blob/master/web/cities/cities-ets2.js
