### ISSUE TITLE
Dark Theme improvements Missing Playbutton

### ISSUE THREAD

**Issue by Chickenbreadlp** [Koenvh1/ets2-local-radio#80]
So, I just noticed a little oversight of mine, where the Play Button for the stations is missing, with the new dark theme. The URL for the Play Button icon needs to bo changed from `../../img/play-button.png` to `../img/play-button.png`

**Comment by Koenvh1** [comment]
Should be fixed in https://github.com/Koenvh1/ets2-local-radio/commit/a1339cc63ac4f1fa2dd694006614871ae54cdf70
