### ISSUE TITLE
Alternative telemetry.dll? 404 error

### ISSUE THREAD

**Issue by cudi90** [Koenvh1/ets2-local-radio#82]
Hello

I have the program constantly showing that ETS2 is not running although it is running. 
Now I wanted to download the alternative ets2-telemetry.dll, but I always get the 404 error message from Github. The file doesn't seem to be available anymore. 

Could the developer upload the alternative .dll again and post it here? 

Thanks a lot!

**Comment by Koenvh1** [comment]
Will fix that. In the meantime, you should be able to find it here: https://github.com/Koenvh1/ets2-local-radio/blob/v1.41.0/plugins/alternative_ets2-telemetry.dll/ets2-telemetry.dll
