### ISSUE TITLE
Download speed very slow

### ISSUE THREAD

**Issue by brocalypepper** [Koenvh1/ets2-local-radio#84]
I'm trying to download the file but every time I do, the speed is around 30 KB/s and eventually it will drop to 0 KB/s. Every other download is fine except this one on GitHub.

**Comment by Koenvh1** [comment]
The download is provided by GitHub, which in turn uses AWS. I don't see any
incidents reported for both.

**Comment by brocalypepper** [comment]
Would it be possible to get the download from an alternative link? I have tried almost everything to fix this but it is not working.

**Comment by Koenvh1** [comment]
https://we.tl/t-evV9hTGVcV should work the next 7 days

**Comment by brocalypepper** [comment]
Thank you!
