### ISSUE TITLE
Overlay gradually increases VRAM usage and crashes the driver.

### ISSUE THREAD

**Issue by AleksaDjrodjic** [Koenvh1/ets2-local-radio#85]
I was fiddling around with the client side, was interested how its working.

I made it spam the overlay over and over again, what i noticed was that the VRAM usage was just increasing and wasn't decreasing when the overlay was set to not render anything.
... paused it, VRAM stopped increasing, resumed it, VRAM started increasing again, its something with the overlay.

The problem is that after a n # of renders, it fills up the whole VRAM and crashes the graphics driver.
On modern cards, this isnt a problem but on something like Intel's iGPUs and old cards it happens quite quickly.

I did my testing on:
RX 580 - 8Gb
R7 240 - 2Gb
and Intel HD from i3 330m with 64Mb of RAM allocated to it.
(It happened quite often on the Intel HD, every ~200 overlay renders and it crashes it)

Was fiddling around to see if i can fix it somehow but i didnt really understand how it renders it and idk how to debug the injected DLL from the game...

Im not expecting this to be fixed or something, i just wanna ask if there is a fix for it and/or if someone can explain to me how exactly the rendering is done and i can try to fix it and request a merge for the fix.

**Comment by Koenvh1** [comment]
I assume the reason is that I forget to dispose something, which means that the overlay image remains in the buffer. I have yet to test it, but I believe the cause is that [this](https://github.com/Koenvh1/ets2-local-radio/blob/master/server/ETS2%20Local%20Radio%20desktop/Station.cs#L71) Bitmap is never disposed.. whoops, sorry about that.

**Comment by Koenvh1** [comment]
Oh, and to answer your second question: The actual rendering is done using https://github.com/spazzarama/Direct3DHook

**Comment by AleksaDjrodjic** [comment]
I dont think its that, i did dispose both the image and the bitmap when i was testing and still nothing.
The thing is, its not the server side that is using up VRAM/RAM, its the game itself, the injected DLL.

Thanks for the link

**Comment by AleksaDjrodjic** [comment]
Could it be this something like this?
https://github.com/spazzarama/Direct3DHook/issues/66

**Comment by AleksaDjrodjic** [comment]
Huh, downloaded the repo again and added that bitmap to be disposed and its working fine now ...
Looks like i might have messed up something somehow, sorry for opening this issue xD

**Comment by AleksaDjrodjic** [comment]
Yeah, ok, nvmd, sorry for closing and opening it ...

Looks like it was that, not disposing the bitmap, altho im not sure why it didnt work when i did testing with stuff that i modified ...
I guess i added something else that that i forgot to dispose or ... i dont know ...

Long story short, that fixed it xD
