### ISSUE TITLE
Overlay on ETS 1.35.2.5

### ISSUE THREAD

**Issue by veso266** [Koenvh1/ets2-local-radio#87]
Hi there I am trying to draw some image over my ETS2 but aperently I cannot find d3d9.dll in win_x64 or win_x86 folder anymore

So I was wondering is Overlay still supported on this version(or the newest one) of ETS2 

because IIRC you needed to ovveride this dll with a patched one to be able to hook into the DX engine and draw over the game

I also looked in my older game version (incase I missed something) 1.27.1.7 and DLL is present in both versions x86 and x64

So I was wondering is it still possible to draw over the game now?, did you find a workaround to maybe patch something else other than dll?

**Comment by Koenvh1** [comment]
Since version 2 it uses a new hooking method that supports DirectX 9 and 11, and no longer relies on the d3d9.dll. That's probably why you cannot find it. It's the "Capture" project of the solution, that's based on https://github.com/spazzarama/Direct3DHook

**Comment by veso266** [comment]
aha

BTW: Not sure how you are coping with this, but if I start my test app and then start ETS2, the game screen is black, if I then quit my app the game returns to normal, but if I launch my program after ETS2 is launched  it works

**Comment by Koenvh1** [comment]
I am not sure what happens there, but the project above does contain an example program as well that you can test with and adapt to whatever you want it to do.
