### ISSUE TITLE
custom.js not loading

### ISSUE THREAD

**Issue by inyashadow** [Koenvh1/ets2-local-radio#88]
Hi,

V3.0.0 not loading custom.js, I tried to add those lines:
cities = cities.concat(cities_yksrsk); //YKSRSK
cities = cities.concat(cities_romania_extended); //Romani

but no luck. Can you give any advise on this?
Apart from that everything works good.

**Comment by inyashadow** [comment]
I did a workaround for this now. Installed version v2.5 and replaced station and cities files from v3.0.

**Comment by Koenvh1** [comment]
I just noticed that I never included `custom.js` support for the map view. That should be fixed soon. The cities themselves should be working regardless though.
