### ISSUE TITLE
Feature Request: Show ONLY current country in map

### ISSUE THREAD

**Issue by N95JPL** [Koenvh1/ets2-local-radio#90]
Hello,
Would it be possible to add a function to the Map, to only show the radio circles from the players current country?
At present, the map is kind of chaotic and takes a while to remove all the filters!

Thanks,
N95JPL

**Comment by Koenvh1** [comment]
Sure, that is technically possible, but may I ask why you want that? The map is mostly an interesting visual, and a tool for me to find gaps in coverage, so I honestly don't know how others use it, hence the question.

**Comment by N95JPL** [comment]
I mainly use it to see what channels I have around me, which one's I will have for a while, opposed to losing signal (Static building up) quickly, depending on how I am traversing a country.
Also, the overlay in game, is the "web view" showing all of the available stations able to be shown/interact through that - or is it just to show which channel you are switching too?

**Comment by Koenvh1** [comment]
There is a show/hide all now, so that should do the trick.
